spring:
  application:
    name: recieppy-api

server:
  port: 8000

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true

---

spring:
  profiles: development

  application:
    name: recieppy-dev-api

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

---

spring:
  profiles: production

  application:
    name: recieppy-api

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
