spring:
  application:
    name: recieppy-api

  mail:
    host: localhost

server:
  port: ${SERVER_PORT:8000}

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

---

spring:
  profiles: development

  application:
    name: recieppy-dev-api

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${OAUTH2_JWT_ENDPOINT}

---

spring:
  profiles: production

  application:
    name: recieppy-api

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${OAUTH2_JWT_ENDPOINT}
