spring:
  application:
    name: recieppy-api

  mail:
    host: 172.17.0.1

  # THYMELEAF (ThymeleafAutoConfiguration)
  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/
    excluded-view-names: # comma-separated list of view names   that should be excluded from resolution
    view-names: # comma-separated list of view names that can be resolved
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html # ;charset=<encoding> is added
    cache: true # set to false for hot refresh

server:
  port: ${SERVER_PORT:8000}

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

---

spring:
  config:
    activate:
      on-profile: development

  application:
    name: recieppy-dev-api

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  security:
    oauth2:
      resourceserver:
        jwt:
          issuers:
            - name: Keycloak
              issuer-uri: ${OAUTH2_ISSUER_URI}
              jwk-set-uri: ${OAUTH2_JWK_URI}
            - name: Supabase
              issuer-uri: ${SUPABASE_ISSUER_URI}
              jwk-set-uri: ${SUPABASE_JWT_SECRET}

---

spring:
  config:
    activate:
      on-profile: production

  application:
    name: recieppy-api

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  security:
    oauth2:
      resourceserver:
        jwt:
          issuers:
            - name: Keycloak
              issuer-uri: ${OAUTH2_ISSUER_URI}
              jwk-set-uri: ${OAUTH2_JWK_URI}
            - name: Supabase
              issuer-uri: ${SUPABASE_ISSUER_URI}
              jwk-set-uri: ${SUPABASE_JWT_SECRET}