
name: build_feature

on:
  push:
    branches:
      - feature/*
  pull_request:
    branches: [ develop ]
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Gradle build
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: build