
name: build-push-stage

on:
  push:
    branches:
      - master
      - feature/*
    repository_dispatch:
        types: run-workflow
  pull_request:
    branches: [ develop ]
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '11'

    # Set app version as environment variable
    - name: Set app version
      run: |
        export BUILD_VERSION=$(grep "version" build.gradle | awk 'NR==2{ split($3,a,"'\''"); print tolower(a[2]) }')
        echo "::set-env name=VERSION_NAME::$BUILD_VERSION"

    # Create Firebase Account file
    - name: Create Firebase account file
      run: |
        mkdir src/main/resources/config
        touch src/main/resources/config/${{ secrets.FIREBASE_ACCOUNT_FILE }}
        echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" >> src/main/resources/config/${{ secrets.FIREBASE_ACCOUNT_FILE }}

    # Build app with Gradle
    - name: Build
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: bootJar

    # Build and push docker image
    - name: Build Docker image
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: laerdh/recieppy-api
        tags: ${{ env.VERSION_NAME }}
        tag_with_sha: true

  push:
    needs: build
    runs-on: ubuntu-latest

    steps:
    
      # Deploy to test
    - name: Run deploy script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: ${{ secrets.SSH_DEPLOY_TEST }} -r ${{ secrets.DOCKER_USERNAME }} -t ${{ secrets.DOCKER_PASSWORD }} -i {{ env.VERSION_NAME }} -l ${{ secrets.DATABASE_URL_TEST }} -d ${{ secrets.DATABASE_SCHEMA_TEST }} -u ${{ secrets.DATABASE_USER_TEST }} -p ${{ secrets.DATABASE_PASSWORD_TEST }} -v ${{ secrets.OIDC_JWT_ENDPOINT }}