# This is a basic workflow to help you get started with Actions

name: build-push-stage

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
      - feature/*
    repository_dispatch:
        types: run-workflow
  pull_request:
    branches: [ develop ]
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '11'

    # Set app version as environment variable
    - name: Set app version
      run: |
        export BUILD_VERSION=$(grep "version" build.gradle | awk 'NR==2{ split($3,a,"'\''"); print tolower(a[2]) }').$GITHUB_SHA
        echo "::set-env name=APP_VERSION::$BUILD_VERSION"

    # Create Firebase Account file
    - name: Create Firebase account file
      run: |
        echo Create Firebase Account file
        mkdir src/main/resources/config
        touch src/main/resources/config/${{ secrets.FIREBASE_ACCOUNT_FILE }}
        echo Touch file
        echo $(ls src/main/resources/config/)
        echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" >> src/main/resources/config/${{ secrets.FIREBASE_ACCOUNT_FILE }}
        echo Injecting filecontent

    # Build app with Gradle
    - name: Build
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: bootJar
        
